"""Remove title column

Revision ID: 1858965fd14e
Revises: 122e90587a60
Create Date: 2021-12-10 08:03:43.821328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1858965fd14e'
down_revision = '122e90587a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=32), nullable=True))

    # ### end Alembic commands ###
